package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ActualPayments generated by hbm2java
 */
@XmlRootElement(name = "actual_payments")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "actual_payments", catalog = "student_loans")
public class ActualPayments implements java.io.Serializable {
	@XmlElement
	private int actualPaymentId;
	@XmlElement
	private Students students;
	@XmlElement
	private Date actualPaymentDate;
	@XmlElement
	private String actualPaymentAmount;
	@XmlElement
	private String otherPaymentDetails;

	public ActualPayments() {
	}

	public ActualPayments(int actualPaymentId) {
		this.actualPaymentId = actualPaymentId;
	}

	public ActualPayments(int actualPaymentId, Students students, Date actualPaymentDate, String actualPaymentAmount,
			String otherPaymentDetails) {
		this.actualPaymentId = actualPaymentId;
		this.students = students;
		this.actualPaymentDate = actualPaymentDate;
		this.actualPaymentAmount = actualPaymentAmount;
		this.otherPaymentDetails = otherPaymentDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "actual_payment_id", unique = true, nullable = false)
	public int getActualPaymentId() {
		return this.actualPaymentId;
	}

	public void setActualPaymentId(int actualPaymentId) {
		this.actualPaymentId = actualPaymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "actual_payment_date", length = 10)
	public Date getActualPaymentDate() {
		return this.actualPaymentDate;
	}

	public void setActualPaymentDate(Date actualPaymentDate) {
		this.actualPaymentDate = actualPaymentDate;
	}

	@Column(name = "actual_payment_amount", length = 45)
	public String getActualPaymentAmount() {
		return this.actualPaymentAmount;
	}

	public void setActualPaymentAmount(String actualPaymentAmount) {
		this.actualPaymentAmount = actualPaymentAmount;
	}

	@Column(name = "other_payment_details", length = 45)
	public String getOtherPaymentDetails() {
		return this.otherPaymentDetails;
	}

	public void setOtherPaymentDetails(String otherPaymentDetails) {
		this.otherPaymentDetails = otherPaymentDetails;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((actualPaymentAmount == null) ? 0 : actualPaymentAmount.hashCode());
		result = prime * result + ((actualPaymentDate == null) ? 0 : actualPaymentDate.hashCode());
		result = prime * result + ((otherPaymentDetails == null) ? 0 : otherPaymentDetails.hashCode());
		result = prime * result + ((students == null) ? 0 : students.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ActualPayments other = (ActualPayments) obj;
		if (actualPaymentAmount == null) {
			if (other.actualPaymentAmount != null)
				return false;
		} else if (!actualPaymentAmount.equals(other.actualPaymentAmount))
			return false;
		if (actualPaymentDate == null) {
			if (other.actualPaymentDate != null)
				return false;
		} else if (!actualPaymentDate.equals(other.actualPaymentDate))
			return false;
		if (otherPaymentDetails == null) {
			if (other.otherPaymentDetails != null)
				return false;
		} else if (!otherPaymentDetails.equals(other.otherPaymentDetails))
			return false;
		if (students == null) {
			if (other.students != null)
				return false;
		} else if (!students.equals(other.students))
			return false;
		return true;
	}

}
