package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Guarantors generated by hbm2java
 */
@XmlRootElement(name = "guarantors")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "guarantors", catalog = "student_loans")
public class Guarantors implements java.io.Serializable {
	@XmlElement
	private int guarantorId;
	@XmlElement
	private Addresses addresses;
	@XmlElement
	private String guarantorName;
	@XmlElement
	private String guarantorEmail;
	@XmlElement
	private String guarantorPhone;
	@XmlElement
	private String otherGuarantorDetails;
	private Set<StudentLoans> studentLoanses = new HashSet<StudentLoans>(0);

	public Guarantors() {
	}

	public Guarantors(int guarantorId) {
		this.guarantorId = guarantorId;
	}

	public Guarantors(int guarantorId, Addresses addresses, String guarantorName, String guarantorEmail,
			String guarantorPhone, String otherGuarantorDetails, Set<StudentLoans> studentLoanses) {
		this.guarantorId = guarantorId;
		this.addresses = addresses;
		this.guarantorName = guarantorName;
		this.guarantorEmail = guarantorEmail;
		this.guarantorPhone = guarantorPhone;
		this.otherGuarantorDetails = otherGuarantorDetails;
		this.studentLoanses = studentLoanses;
	}

	@Id

	@Column(name = "guarantor_id", unique = true, nullable = false)
	public int getGuarantorId() {
		return this.guarantorId;
	}

	public void setGuarantorId(int guarantorId) {
		this.guarantorId = guarantorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id")
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@Column(name = "guarantor_name", length = 45)
	public String getGuarantorName() {
		return this.guarantorName;
	}

	public void setGuarantorName(String guarantorName) {
		this.guarantorName = guarantorName;
	}

	@Column(name = "guarantor_email", length = 45)
	public String getGuarantorEmail() {
		return this.guarantorEmail;
	}

	public void setGuarantorEmail(String guarantorEmail) {
		this.guarantorEmail = guarantorEmail;
	}

	@Column(name = "guarantor_phone", length = 45)
	public String getGuarantorPhone() {
		return this.guarantorPhone;
	}

	public void setGuarantorPhone(String guarantorPhone) {
		this.guarantorPhone = guarantorPhone;
	}

	@Column(name = "other_guarantor_details", length = 45)
	public String getOtherGuarantorDetails() {
		return this.otherGuarantorDetails;
	}

	public void setOtherGuarantorDetails(String otherGuarantorDetails) {
		this.otherGuarantorDetails = otherGuarantorDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "guarantors")
	public Set<StudentLoans> getStudentLoanses() {
		return this.studentLoanses;
	}

	public void setStudentLoanses(Set<StudentLoans> studentLoanses) {
		this.studentLoanses = studentLoanses;
	}

}
