package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PlannedPayments generated by hbm2java
 */
@XmlRootElement(name = "planned_payments")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "planned_payments", catalog = "student_loans")
public class PlannedPayments implements java.io.Serializable {
	@XmlElement
	private int regularOrderId;
	@XmlElement
	private RefPaymentStatus refPaymentStatus;
	@XmlElement
	private Students students;
	@XmlElement
	private Date paymentDueDate;
	@XmlElement
	private String plannedPaymentAmount;
	@XmlElement
	private String otherPaymentDetails;

	public PlannedPayments() {
	}

	public PlannedPayments(int regularOrderId) {
		this.regularOrderId = regularOrderId;
	}

	public PlannedPayments(int regularOrderId, RefPaymentStatus refPaymentStatus, Students students,
			Date paymentDueDate, String plannedPaymentAmount, String otherPaymentDetails) {
		this.regularOrderId = regularOrderId;
		this.refPaymentStatus = refPaymentStatus;
		this.students = students;
		this.paymentDueDate = paymentDueDate;
		this.plannedPaymentAmount = plannedPaymentAmount;
		this.otherPaymentDetails = otherPaymentDetails;
	}

	@Id

	@Column(name = "regular_order_id", unique = true, nullable = false)
	public int getRegularOrderId() {
		return this.regularOrderId;
	}

	public void setRegularOrderId(int regularOrderId) {
		this.regularOrderId = regularOrderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_status_code")
	public RefPaymentStatus getRefPaymentStatus() {
		return this.refPaymentStatus;
	}

	public void setRefPaymentStatus(RefPaymentStatus refPaymentStatus) {
		this.refPaymentStatus = refPaymentStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_due_date", length = 10)
	public Date getPaymentDueDate() {
		return this.paymentDueDate;
	}

	public void setPaymentDueDate(Date paymentDueDate) {
		this.paymentDueDate = paymentDueDate;
	}

	@Column(name = "planned_payment_amount", length = 45)
	public String getPlannedPaymentAmount() {
		return this.plannedPaymentAmount;
	}

	public void setPlannedPaymentAmount(String plannedPaymentAmount) {
		this.plannedPaymentAmount = plannedPaymentAmount;
	}

	@Column(name = "other_payment_details", length = 45)
	public String getOtherPaymentDetails() {
		return this.otherPaymentDetails;
	}

	public void setOtherPaymentDetails(String otherPaymentDetails) {
		this.otherPaymentDetails = otherPaymentDetails;
	}

}
