package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * RefAccountTypes generated by hbm2java
 */
@XmlRootElement(name = "ref_account_types")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "ref_account_types", catalog = "student_loans")
public class RefAccountTypes implements java.io.Serializable {
	@XmlElement
	private String accountTypeCode;
	@XmlElement
	private String accountTypeDescription;
	
	private Set<Accounts> accountses = new HashSet<Accounts>(0);

	public RefAccountTypes() {
	}

	public RefAccountTypes(String accountTypeCode) {
		this.accountTypeCode = accountTypeCode;
	}

	public RefAccountTypes(String accountTypeCode, String accountTypeDescription, Set<Accounts> accountses) {
		this.accountTypeCode = accountTypeCode;
		this.accountTypeDescription = accountTypeDescription;
		this.accountses = accountses;
	}

	@Id

	@Column(name = "account_type_code", unique = true, nullable = false, length = 45)
	public String getAccountTypeCode() {
		return this.accountTypeCode;
	}

	public void setAccountTypeCode(String accountTypeCode) {
		this.accountTypeCode = accountTypeCode;
	}

	@Column(name = "account_type_description", length = 45)
	public String getAccountTypeDescription() {
		return this.accountTypeDescription;
	}

	public void setAccountTypeDescription(String accountTypeDescription) {
		this.accountTypeDescription = accountTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refAccountTypes")
	public Set<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set<Accounts> accountses) {
		this.accountses = accountses;
	}

}
