package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * RefBanks generated by hbm2java
 */
@XmlRootElement(name = "ref_banks")
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "ref_banks", catalog = "student_loans")
public class RefBanks implements java.io.Serializable {
	@XmlElement
	private String bankCode;
	@XmlElement
	private String bankName;
	
	private Set<Accounts> accountses = new HashSet<Accounts>(0);

	public RefBanks() {
	}

	public RefBanks(String bankCode) {
		this.bankCode = bankCode;
	}

	public RefBanks(String bankCode, String bankName, Set<Accounts> accountses) {
		this.bankCode = bankCode;
		this.bankName = bankName;
		this.accountses = accountses;
	}

	@Id

	@Column(name = "bank_code", unique = true, nullable = false, length = 45)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "bank_name", length = 45)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refBanks")
	public Set<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set<Accounts> accountses) {
		this.accountses = accountses;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RefBanks other = (RefBanks) obj;
		if (bankCode == null) {
			if (other.bankCode != null)
				return false;
		} else if (!bankCode.equals(other.bankCode))
			return false;
		if (bankName == null) {
			if (other.bankName != null)
				return false;
		} else if (!bankName.equals(other.bankName))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "RefBanks [bankCode=" + bankCode + ", bankName=" + bankName + "]";
	}
	
}
