package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefLoanStatus generated by hbm2java
 */
@Entity
@Table(name = "ref_loan_status", catalog = "student_loans")
public class RefLoanStatus implements java.io.Serializable {

	private String loanStatusCode;
	private String loanStatusDescription;
	private Set<StudentLoans> studentLoanses = new HashSet<StudentLoans>(0);

	public RefLoanStatus() {
	}

	public RefLoanStatus(String loanStatusCode) {
		this.loanStatusCode = loanStatusCode;
	}

	public RefLoanStatus(String loanStatusCode, String loanStatusDescription, Set<StudentLoans> studentLoanses) {
		this.loanStatusCode = loanStatusCode;
		this.loanStatusDescription = loanStatusDescription;
		this.studentLoanses = studentLoanses;
	}

	@Id

	@Column(name = "loan_status_code", unique = true, nullable = false, length = 45)
	public String getLoanStatusCode() {
		return this.loanStatusCode;
	}

	public void setLoanStatusCode(String loanStatusCode) {
		this.loanStatusCode = loanStatusCode;
	}

	@Column(name = "loan_status_description", length = 45)
	public String getLoanStatusDescription() {
		return this.loanStatusDescription;
	}

	public void setLoanStatusDescription(String loanStatusDescription) {
		this.loanStatusDescription = loanStatusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLoanStatus")
	public Set<StudentLoans> getStudentLoanses() {
		return this.studentLoanses;
	}

	public void setStudentLoanses(Set<StudentLoans> studentLoanses) {
		this.studentLoanses = studentLoanses;
	}

}
