package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StandardLoans generated by hbm2java
 */
@Entity
@Table(name = "standard_loans", catalog = "student_loans")
public class StandardLoans implements java.io.Serializable {

	private int standardLoanId;
	private String standardLoanName;
	private String standardLoanMinAmount;
	private String standardLoanMaxAmount;
	private String standardLoanPeriod;
	private String standardLoanDescription;
	private String standardLoanDetails;
	private Set<StudentLoans> studentLoanses = new HashSet<StudentLoans>(0);

	public StandardLoans() {
	}

	public StandardLoans(int standardLoanId) {
		this.standardLoanId = standardLoanId;
	}

	public StandardLoans(int standardLoanId, String standardLoanName, String standardLoanMinAmount,
			String standardLoanMaxAmount, String standardLoanPeriod, String standardLoanDescription,
			String standardLoanDetails, Set<StudentLoans> studentLoanses) {
		this.standardLoanId = standardLoanId;
		this.standardLoanName = standardLoanName;
		this.standardLoanMinAmount = standardLoanMinAmount;
		this.standardLoanMaxAmount = standardLoanMaxAmount;
		this.standardLoanPeriod = standardLoanPeriod;
		this.standardLoanDescription = standardLoanDescription;
		this.standardLoanDetails = standardLoanDetails;
		this.studentLoanses = studentLoanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "standard_loan_id", unique = true, nullable = false)
	public int getStandardLoanId() {
		return this.standardLoanId;
	}

	public void setStandardLoanId(int standardLoanId) {
		this.standardLoanId = standardLoanId;
	}

	@Column(name = "standard_loan_name", length = 45)
	public String getStandardLoanName() {
		return this.standardLoanName;
	}

	public void setStandardLoanName(String standardLoanName) {
		this.standardLoanName = standardLoanName;
	}

	@Column(name = "standard_loan_min_amount", length = 45)
	public String getStandardLoanMinAmount() {
		return this.standardLoanMinAmount;
	}

	public void setStandardLoanMinAmount(String standardLoanMinAmount) {
		this.standardLoanMinAmount = standardLoanMinAmount;
	}

	@Column(name = "standard_loan_max_amount", length = 45)
	public String getStandardLoanMaxAmount() {
		return this.standardLoanMaxAmount;
	}

	public void setStandardLoanMaxAmount(String standardLoanMaxAmount) {
		this.standardLoanMaxAmount = standardLoanMaxAmount;
	}

	@Column(name = "standard_loan_period", length = 45)
	public String getStandardLoanPeriod() {
		return this.standardLoanPeriod;
	}

	public void setStandardLoanPeriod(String standardLoanPeriod) {
		this.standardLoanPeriod = standardLoanPeriod;
	}

	@Column(name = "standard_loan_description", length = 45)
	public String getStandardLoanDescription() {
		return this.standardLoanDescription;
	}

	public void setStandardLoanDescription(String standardLoanDescription) {
		this.standardLoanDescription = standardLoanDescription;
	}

	@Column(name = "standard_loan_details", length = 45)
	public String getStandardLoanDetails() {
		return this.standardLoanDetails;
	}

	public void setStandardLoanDetails(String standardLoanDetails) {
		this.standardLoanDetails = standardLoanDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "standardLoans")
	public Set<StudentLoans> getStudentLoanses() {
		return this.studentLoanses;
	}

	public void setStudentLoanses(Set<StudentLoans> studentLoanses) {
		this.studentLoanses = studentLoanses;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((standardLoanDescription == null) ? 0 : standardLoanDescription.hashCode());
		result = prime * result + ((standardLoanDetails == null) ? 0 : standardLoanDetails.hashCode());
		result = prime * result + ((standardLoanMaxAmount == null) ? 0 : standardLoanMaxAmount.hashCode());
		result = prime * result + ((standardLoanMinAmount == null) ? 0 : standardLoanMinAmount.hashCode());
		result = prime * result + ((standardLoanName == null) ? 0 : standardLoanName.hashCode());
		result = prime * result + ((standardLoanPeriod == null) ? 0 : standardLoanPeriod.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StandardLoans other = (StandardLoans) obj;
		if (standardLoanDescription == null) {
			if (other.standardLoanDescription != null)
				return false;
		} else if (!standardLoanDescription.equals(other.standardLoanDescription))
			return false;
		if (standardLoanDetails == null) {
			if (other.standardLoanDetails != null)
				return false;
		} else if (!standardLoanDetails.equals(other.standardLoanDetails))
			return false;
		if (standardLoanMaxAmount == null) {
			if (other.standardLoanMaxAmount != null)
				return false;
		} else if (!standardLoanMaxAmount.equals(other.standardLoanMaxAmount))
			return false;
		if (standardLoanMinAmount == null) {
			if (other.standardLoanMinAmount != null)
				return false;
		} else if (!standardLoanMinAmount.equals(other.standardLoanMinAmount))
			return false;
		if (standardLoanName == null) {
			if (other.standardLoanName != null)
				return false;
		} else if (!standardLoanName.equals(other.standardLoanName))
			return false;
		if (standardLoanPeriod == null) {
			if (other.standardLoanPeriod != null)
				return false;
		} else if (!standardLoanPeriod.equals(other.standardLoanPeriod))
			return false;
		return true;
	}

}
