package restfulwebservice.model;
// Generated May 26, 2017 8:19:28 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentAddresses generated by hbm2java
 */
@Entity
@Table(name = "student_addresses", catalog = "student_loans")
public class StudentAddresses implements java.io.Serializable {

	private Date dateFrom;
	private Addresses addresses;
	private RefAddressTypes refAddressTypes;
	private Students students;
	private Date dateTo;

	public StudentAddresses() {
	}

	public StudentAddresses(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public StudentAddresses(Date dateFrom, Addresses addresses, RefAddressTypes refAddressTypes, Students students,
			Date dateTo) {
		this.dateFrom = dateFrom;
		this.addresses = addresses;
		this.refAddressTypes = refAddressTypes;
		this.students = students;
		this.dateTo = dateTo;
	}

	@Id

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", unique = true, nullable = false, length = 10)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id")
	public Addresses getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Addresses addresses) {
		this.addresses = addresses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_type_code")
	public RefAddressTypes getRefAddressTypes() {
		return this.refAddressTypes;
	}

	public void setRefAddressTypes(RefAddressTypes refAddressTypes) {
		this.refAddressTypes = refAddressTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_to", length = 10)
	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

}
